export default function Head() {
  return (
    <>
      <title>on Safari | Little Harbor 38</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
          name="description"
          content="Travel blog of our adventures in the North Atlantic Ocean"
          key="desc"
        />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
